apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: 'mongo-service'
  replicas: 3
  selector:
    matchLabels:
      name: mongo
  template:
    metadata:
      name: mongo
      labels:
        name: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
#DO THIS BEFORE ADD SECURITY
#          command: ["mongod", "--bind_ip", "0.0.0.0", "--replSet", "rs0", "--dbpath", "/mongodata/"]
          command: ["mongod", "--bind_ip", "0.0.0.0", "--replSet", "rs0", "--dbpath", "/mongodata/","-f","/mongodata/mongod.conf"]
          ports:
          - containerPort: 27017
          volumeMounts:
          - name: volume
            mountPath: /mongodata
  volumeClaimTemplates:
  - metadata:
      name: volume
    spec:
      storageClassName: managed-nfs-storage
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi


#kubectl expose pod mongo-0 --type=NodePort --port=27017 --target-port=27017 && kubectl expose pod mongo-1 --type=NodePort --port=27017 --target-port=27017 && kubectl expose pod mongo-2 --type=NodePort --port=27017 --target-port=27017
#kubectl delete service mongo-0 && kubectl delete service mongo-1 && kubectl delete service mongo-2
