apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
    statefulset.kubernetes.io/pod-name: mongo-0
  name: mongo-0
spec:
  ports:
  - nodePort: 30010
    port: 27017
    targetPort: 27017
  selector:
    name: mongo
    statefulset.kubernetes.io/pod-name: mongo-0
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
    statefulset.kubernetes.io/pod-name: mongo-1
  name: mongo-1
spec:
  ports:
  - nodePort: 30020
    port: 27017
    targetPort: 27017
  selector:
    name: mongo
    statefulset.kubernetes.io/pod-name: mongo-1
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
    statefulset.kubernetes.io/pod-name: mongo-2
  name: mongo-2
spec:
  ports:
  - nodePort: 30030
    port: 27017
    targetPort: 27017
  selector:
    name: mongo
    statefulset.kubernetes.io/pod-name: mongo-2
  type: NodePort

