apiVersion: v1
kind: Service
metadata:
  name: mongo-0
spec:
  type: LoadBalancer
  selector:
    name: mongo-0
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 31000
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-1
spec:
  type: LoadBalancer
  selector:
    name: mongo-1
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 32000
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-2
spec:
  type: LoadBalancer
  selector:
    name: mongo-2
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 33000

