apiVersion: v1
kind: Pod
metadata:
  name: mem-limit
  namespace: quota-demo-ns
spec:
  containers:
  - name: memlimit 
    image: polinux/stress
    resources:
      limits:
        memory: "200Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
