version: '2.2'
services:
  rancher:
    image: rancher/rancher:latest
    container_name: rancher
    volumes:
      - rancher-data:/var/lib/rancher
    ports:
      - 80:80
      - 443:443

volumes:
  rancher-data: {}
