apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs1-claim
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
